apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  imagePullPolicy: Always
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: ping-exporter
  template:
    metadata:
      labels:
        app: ping-exporter
    spec:
      serviceAccountName: ping-exporter
      containers:
      - name: ping-exporter
        image: maclucky/kubernetes-ping-exporter-golang
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONFIG_MAP_NAME
          value: "ping-exporter-config"
        ports:
        - containerPort: 9107
          name: metrics
      restartPolicy: Always