kind: Service
apiVersion: v1
metadata:
  name: ping-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: ping-exporter
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ping-exporter
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
