{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-exporter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: ping-exporter
  endpoints:
    - port: {{ .Values.service.name }}
{{- end }}
