apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ping-exporter
  endpoints:
    - port: metrics
