name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    environment: maclucky
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t maclucky/kubernetes-ping-exporter:$(date +%s) .

    - name: Push the Docker image to Docker Hub
      run: docker push maclucky/kubernetes-ping-exporter:$(date +%s)