name: Docker Image for Kubernetes Ping Exporter

on:
  push:
    branches: ["master"]
    paths-ignore:
      - ".github/workflows/**"
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - ".github/workflows/**"
      - "*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    environment: maclucky
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest version tag
        id: get_latest_version
        run: |
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/maclucky/kubernetes-ping-exporter/tags?page_size=100" | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 || echo "")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Set version
        id: set_version
        run: |
          VERSION=${{ env.LATEST_TAG }}
          if [ -z "$VERSION" ]; then
            NEW_VERSION="1.0.0"
          else
            NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          fi
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            maclucky/kubernetes-ping-exporter:${{ env.NEW_VERSION }}
            maclucky/kubernetes-ping-exporter:latest
            ghcr.io/mac-lucky/kubernetes-ping-exporter:${{ env.NEW_VERSION }}
            ghcr.io/mac-lucky/kubernetes-ping-exporter:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max