name: Optimized CI/CD - Kubernetes Ping Exporter

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  release:
    types: [published]

env:
  REGISTRY_IMAGE_DOCKERHUB: maclucky/kubernetes-ping-exporter
  REGISTRY_IMAGE_GHCR: ghcr.io/mac-lucky/kubernetes-ping-exporter

jobs:
  # Job 0: Extract Go version from go.mod
  setup:
    name: Setup Build Environment
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.go-version.outputs.version }}
      go-version-matrix: ${{ steps.go-version.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go version from go.mod
        id: go-version
        run: |
          # Extract Go version from go.mod
          GO_VERSION=$(grep "^go " go.mod | cut -d' ' -f2)
          echo "Found Go version in go.mod: $GO_VERSION"

          # Set primary version for builds
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

          # Create matrix for testing (current version + previous)
          # Extract major.minor and create previous version for testing
          MAJOR_MINOR=$(echo $GO_VERSION | cut -d'.' -f1,2)
          PREV_VERSION="$MAJOR_MINOR"

          # For Go 1.23, test with 1.22 as well
          if [[ $MAJOR_MINOR == "1.23" ]]; then
            PREV_VERSION="1.22"
          elif [[ $MAJOR_MINOR == "1.22" ]]; then
            PREV_VERSION="1.21"
          fi

          # Create JSON array for matrix
          MATRIX="[\"$PREV_VERSION\", \"$GO_VERSION\"]"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "Testing with Go versions: $MATRIX"

  # Job 1: Code Quality & Security Analysis
  code-analysis:
    name: Code Analysis & Security Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.setup.outputs.go-version }}
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"

  # Job 2: Kubernetes Integration Tests
  container-test:
    name: Kubernetes Integration Test
    runs-on: ubuntu-latest
    needs: [setup, code-analysis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: kubernetes-ping-exporter:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ needs.setup.outputs.go-version }}

      - name: Setup Minikube with 2 nodes
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          driver: docker
          container-runtime: docker
          kubernetes-version: v1.32.0
          cpus: 2
          memory: 2048m
          addons: metrics-server
          start-args: '--nodes=2'

      - name: Load Docker image into Minikube
        run: |
          minikube image load kubernetes-ping-exporter:test

      - name: Create monitoring namespace
        run: |
          kubectl create namespace monitoring || true

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Deploy ping-exporter with Helm
        run: |
          helm upgrade --install ping-exporter ./infra-ping-exporter \
            --namespace monitoring \
            --set image.tag=test \
            --set image.repository=kubernetes-ping-exporter \
            --set image.pullPolicy=Never \
            --set serviceMonitor.enabled=false \
            --wait --timeout=300s

      - name: Verify deployment
        run: |
          echo "=== Checking deployment status ==="
          kubectl get pods -n monitoring -l app=ping-exporter -o wide
          kubectl get daemonset -n monitoring
          kubectl get services -n monitoring
          kubectl get configmap -n monitoring

      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=ping-exporter -n monitoring --timeout=120s

      - name: Wait for application startup
        run: |
          echo "=== Waiting 60 seconds for application to fully start ==="
          sleep 60

      - name: Check logs
        run: |
          echo "=== Application logs ==="
          kubectl logs -l app=ping-exporter -n monitoring --tail=50

      - name: Test metrics endpoint via port-forward
        run: |
          echo "=== Testing metrics endpoint ==="
          kubectl port-forward -n monitoring svc/ping-exporter 9107:9107 &
          PF_PID=$!
          sleep 10
          
          # Test metrics endpoint
          response=$(curl -s http://localhost:9107/metrics)
          if echo "$response" | grep -q "ping_duration_seconds"; then
            echo "✅ Metrics endpoint working - ping_duration_seconds found"
            echo "Sample metrics:"
            echo "$response" | head -20
          else
            echo "❌ Metrics endpoint not working - ping_duration_seconds not found"
            echo "Response received:"
            echo "$response"
            exit 1
          fi
          
          # Cleanup
          kill $PF_PID || true

      - name: Health check
        run: |
          echo "=== Health check ==="
          # Check if all pods are running
          READY_PODS=$(kubectl get pods -n monitoring -l app=ping-exporter -o jsonpath='{.items[*].status.phase}' | grep -o Running | wc -l)
          TOTAL_PODS=$(kubectl get pods -n monitoring -l app=ping-exporter --no-headers | wc -l)
          
          echo "Ready pods: $READY_PODS / $TOTAL_PODS"
          
          if [ "$READY_PODS" -eq "$TOTAL_PODS" ] && [ "$TOTAL_PODS" -gt 0 ]; then
            echo "✅ All pods are running successfully"
          else
            echo "❌ Not all pods are running"
            kubectl describe pods -n monitoring -l app=ping-exporter
            exit 1
          fi

      - name: Container security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "kubernetes-ping-exporter:test"
          format: "table"

      - name: Cleanup
        if: always()
        run: |
          helm uninstall ping-exporter -n monitoring || true
          kubectl delete namespace monitoring || true


  # Job 3: Build and Push Multi-arch Container Images
  build-and-push:
    name: Build & Push Container Images
    runs-on: ubuntu-latest
    needs: [setup, code-analysis]
    if: github.event_name == 'push' || github.event_name == 'release'
    environment: maclucky
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest version tag
        id: get_latest_version
        run: |
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/${{ env.REGISTRY_IMAGE_DOCKERHUB }}/tags?page_size=100" | \
            jq -r '.results[].name' | \
            grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | \
            sort -V | tail -n 1 || echo "")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Set version
        id: set_version
        run: |
          VERSION=${{ env.LATEST_TAG }}
          if [ -z "$VERSION" ]; then
            NEW_VERSION="1.0.0"
          else
            NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          fi
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE_DOCKERHUB }}:${{ env.NEW_VERSION }}
            ${{ env.REGISTRY_IMAGE_DOCKERHUB }}:latest
            ${{ env.REGISTRY_IMAGE_GHCR }}:${{ env.NEW_VERSION }}
            ${{ env.REGISTRY_IMAGE_GHCR }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ needs.setup.outputs.go-version }}
            VERSION=${{ env.NEW_VERSION }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY_IMAGE_GHCR }}:${{ env.NEW_VERSION }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  # Job 5: Post-deployment verification
  post-deploy-verify:
    name: Post-deployment Verification
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Verify image pull and functionality
        run: |
          echo "Verifying images can be pulled..."
          docker pull ${{ env.REGISTRY_IMAGE_DOCKERHUB }}:latest

          echo "Testing basic functionality..."
          docker run --rm -d \
            -p 9108:9107 \
            --name verify-container \
            ${{ env.REGISTRY_IMAGE_DOCKERHUB }}:latest

          sleep 15

          # Test that the service responds
          if wget -q --spider http://localhost:9108/metrics; then
            echo "✅ Service verification successful"
          else
            echo "❌ Service verification failed" 
            docker logs verify-container
            exit 1
          fi

          docker stop verify-container
